import type { Metadata } from "next";
import "../globals.css";
import { ToastProvider } from "@/components/ToastContainer";
import ChatNavbar from "@/components/NavChat";


export const metadata: Metadata = {
  title: "NoteX",
  description: "Generated by NoteX",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body >
            <ChatNavbar />
            {children}
            <ToastProvider />
        
        </body>
    </html>
  );
}
