import type { Metadata } from "next";
import "../globals.css";
import { MyProvider } from "../context/store";
import { ToastProvider } from "@/components/ToastContainer";



export const metadata: Metadata = {
  title: "NoteX",
  description: "Generated by NoteX",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body >
        <MyProvider>
          {children}
          <ToastProvider />
        </MyProvider>
        </body>
    </html>
  );
}
